---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: database-ss
  namespace: dev
spec:
  replicas: 1
  serviceName: mysqldb
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      name: temp1
      labels:
        app: database
    spec:
      containers:
        - name: db
          image: manju9676/hopegiversbloodbank-database:30
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_ROOT_PASSWORD
          volumeMounts:
            - name: mysql-pvc
              mountPath: /var/lib/mysql
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
          livenessProbe:
            exec:
              command: ["mysqladmin", "ping", "-h", "localhost"]
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            exec:
              command: ["mysqladmin", "ping", "-h", "localhost"]
            initialDelaySeconds: 50
            periodSeconds: 10


  volumeClaimTemplates:
    - metadata:
        name: mysql-pvc
      spec:
        storageClassName: aws-ebs
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi



